추천 (recommend) 페이지 1을 구성한다.
DonggukBOB/dongguk-bob pull request #16
Opened 2021-05-16 12:48 UTC by win9612

<추가 컴포넌트>
DecoImage : 추천페이지1에 들어갈 데코레이션 용 이미지입니다. 현재 임시 구성
BigButton : 가운데에 크게 들어갈 "Go!" 버튼입니다.

일단 recommend폴더에 넣었고, 이후 팀원들과의 협의를 거쳐 components 폴더로 이동시키면 좋을 것 같습니다.

- 페이지에 들어갈 요소들의 임시 구성 완료
- 컴포넌트들에 적용될 애니메이션은 추후 협의 필요

2021-05-17 12:29 UTC, hwookim requested changes
yarn 파일 삭제해주세요.
하나의 프로젝트에 두개의 패키지 관리자는 필요 없는 거 같아요.

아예 yarn으로 바꿀까요?
그렇다면 그건 논의 후 다른 이슈를 통해 진행하는 게 맞을 것 같습니다.

---

굳이 큰 기능이 없고, 여러 컴포넌트에서의 재사용성이 없다면 컴포넌트로 분리할 필요는 없습니다.
되려 보일러플레이트를 늘리고 관리할 코드의 양만 많아지게 되니까요.

한 컴포넌트 내에서 반복되는 부분은 이런 식으로도 만들 수 있습니다.
```javascript
const Image = `<img src="~~" alt="이미지" />`;
```
간단하게 반복 부분만 빼서 선언하고 쓰면 됩니다.

---

안쓰는 코드는 되도록 지워주세요.
쌓아두다보면 나중에 힘들어집니다.

2021-05-17 12:29 UTC, hwookim commented on src/pages/recommend/BigButton.jsx
> +    </Container>
모달창을 띄우기로 했기 때문에 Link로 감쌀 필요는 없을 거 같아요.
url이 바뀔 필요도 없구요.

컨테이너로 감쌀 필요가 있나요?
컴포넌트로 나뉠 필요가 있는지도 잘 모르겠네요.

2021-05-17 12:29 UTC, hwookim commented on src/pages/recommend/DecoImage.jsx
> +*/
불필요한 코드는 삭제해주세요

2021-05-17 12:29 UTC, hwookim commented on src/pages/recommend/BigButton.jsx
> +export default function BigButton() {
BigButton이라는 네이밍은 좀....
RecommendButton 같은 걸로 '역할'을 명시해주세요.

2021-05-17 12:29 UTC, hwookim commented on src/pages/recommend/index.jsx
> +      </Container>
어... 좀 많이 구립니다....
그냥 차라리 버튼만 있는 게 나을 거 같아요...

2021-05-17 12:29 UTC, hwookim commented on src/pages/recommend/result.jsx
> +
prettier 안돌리셨나요? 탭사이즈가..

해당 컴포넌트가 왜 recommend 패키지 안에 있나요.
왜 파일명은 result죠? 컴포넌트랑 맞춰야하지 않을까요.

애초에 필요 없는 컴포넌트인 거 같아요.
이슈 범위 외의 개발은 지양해주세요.

2021-05-17 12:29 UTC, hwookim commented on src/pages/recommend/DecoImage.jsx
> +}
div로 굳이 감쌀 필요 없을 거 같아요.

별달리 기능도 없다면 굳이 다른 컴포넌트로 뺄 필요는 없어 보입니다.
되도록이면 파일명에 한글은 지양해주세요.

2021-05-17 12:29 UTC, hwookim commented on package.json
> +    "react-slick": "^0.28.1",
쓰나요?

2021-05-20 05:04 UTC, win9612 commented on src/pages/recommend/BigButton.jsx
> +    </Container>
Container는 후에 버튼 외 다른 요소를 고려하여 만들어놨습니다. 내일 협의 후 버튼만 남기는걸로 결정되면 제거하도록 하겠습니다. link는 삭제했어요!

2021-05-20 05:04 UTC, win9612 commented on src/pages/recommend/DecoImage.jsx
> +*/
넵 삭제했어요

2021-05-20 05:04 UTC, win9612 commented on src/pages/recommend/BigButton.jsx
> +export default function BigButton() {
컴포넌트 이름 BigButton -> RecommendButton 으로 변경하였습니다

2021-05-20 05:05 UTC, win9612 commented on src/pages/recommend/index.jsx
> +      </Container>
넵 우선 버튼만 남겼습니다

2021-05-20 05:05 UTC, win9612 commented on src/pages/recommend/result.jsx
> +
result.jsx 삭제했습니다

2021-05-20 05:05 UTC, win9612 commented on src/pages/recommend/DecoImage.jsx
> +}
DecoImage 컴포넌트 삭제하였습니다.

2021-05-20 05:06 UTC, win9612 commented on package.json
> +    "react-slick": "^0.28.1",
추후 개발 진행하면서 넣을까 생각중이었습니다.
필요할 때 넣고 지금은 지울게요

2021-05-20 17:49 UTC, hwookim requested changes
안쓰이는 이미지 파일은 지워주시면 좋을 것 같습니다.

버튼을 굳이 컴포넌트로 분리해야하는지 의문입니다.
추천 로직은 어차피 분리할 수 있고, 버튼 자체에는 로직 호출 외의 큰 역할이 없기 때문에 분리할 필요성이 적어 보입니다.

추천 페이지 컴포넌트 내에서 아래와 같이 스타일을 적용하면 의도하신 중앙 정렬이 가능합니다
```javascript
const Container = styled.div`
  display: flex;
  height: 100%;
  flex-direction: column;
`;

const Button = styled.button`
  margin: auto;
  width: 4em;
  height: 4em;
  border: 0.1em solid #ffcc5c;
  border-radius: 1em;
  background-color: #fbc402;
  font-size: 5em;
`;

export default function RecommendPage() {
  return (
    <Container>
      <Header />
      <Button>Go!</Button>
    </Container>
  );
}
```
여기서 중앙 정렬을 하는 코드는 단 한줄 `margin: auto` 뿐 입니다.
물론 다른 방식도 많습니다.

2021-05-20 17:49 UTC, hwookim commented on src/pages/recommend/index.jsx
> +`;
지금으로서는 아무 역할도 하지 않는 스타일이네요

2021-05-20 17:49 UTC, hwookim commented on src/pages/recommend/RecommendButton.jsx
> +  font-size: 5em;
컴포넌트로 분리하는 목적은 재사용성 혹은 역할의 분리입니다.
하지만 해당 컴포넌트는 재사용성이 없을 뿐더러 내부 코드도 없네요.
굳이 분리해야할까요?

버튼과 같은 컴포넌트를 분리할 때,
상위 컴포넌트에서 어떤 위치를 잡을지를 하위 컴포넌트에서 설정하면 안됩니다.
다른 컴포넌트에서 사용될 때, 혹은 상위 컴포넌트에 뭔가 추가되었을 때 어떻게 변할지 모르기 때문이죠.
가운데 정렬을 하고싶으신거라면 recommend 페이지 내에서 진행하시는 것이 바람직합니다.

참고로 현재 `margin: 0 auto;` 라인은 아무 역할을 하지 않습니다.
별도로 선언하신 `Container`도 아무 역할을 하지 않고요.

스타일의 경우엔 내일 한 번 더 말해야겠지만,
개인적으로는 최소한 #15 의 버튼과는 통일하면 좋을 것 같아요.
border같은 경우에는, 만약 사용한다면 em보다는 일정한 게 더 나을 듯 합니다.

2021-05-21 05:17 UTC, win9612 commented on src/pages/recommend/index.jsx
> +`;
삭제하고 위의 css 스타일을 반영하여 구성했습니다

2021-05-21 05:19 UTC, win9612 commented on src/pages/recommend/RecommendButton.jsx
> +  font-size: 5em;
맞네요, 하나의 페이지 안에서만 쓰이는 컴포넌트면 페이지 안에 넣는게 맞는 것 같습니다. RecommendButton.jsx 컴포넌트 삭제하고 recommend/index.jsx에 통합했어요. 버튼 스타일은 한번 얘기해보고 통일할게요

2021-05-21 12:19 UTC, hwookim approved these changes
👍🏼

2021-05-21 12:20 UTC, merged