필터를 구현한다.
DonggukBOB/dongguk-bob pull request #32
Opened 2021-05-31 09:11 UTC by GyeongyeonAn

close #26

![image](https://user-images.githubusercontent.com/55589616/120170014-7f53f600-c23b-11eb-957f-37b509667a03.png)

![image](https://user-images.githubusercontent.com/55589616/120170068-8c70e500-c23b-11eb-972b-fc4b4dc9a42c.png)

![image](https://user-images.githubusercontent.com/55589616/120170102-9397f300-c23b-11eb-8272-4d04e1adf742.png)

피드백 부탁드립니다.

2021-05-31 09:14 UTC, GyeongyeonAn commented
아래 그림처럼 필터 버튼을 눌렀을 때 현재 카테고리 색을 유지하도록 설계하고 싶었는데 어려워 하지를 못했습니다..

![image](https://user-images.githubusercontent.com/55589616/120170430-e96c9b00-c23b-11eb-8e8e-5c62df9fca75.png)

방법을 알면 가르쳐 주시면 감사합니다....

2021-05-31 12:13 UTC, hwookim requested changes
코드의 중복을 최소화할 수 있는 방법에 뭐가 있을지 한 번 생각해보면 좋을 것 같네요.

추천 페이지에도 추가해주세요 그리고 ㅎㅎ

2021-05-31 12:13 UTC, hwookim commented on src/components/Filter.jsx
> +    }
```suggestion
    $(".location-filter-items").toggle();
    $(".price-filter-items").hide();
    $(".category-filter-items").hide();
```
코드 자체는 이게 더 간단할 거 같아요.

local, price, category 모두 비슷한 코드를 공유하는데 중복을 제거할 수는 없을까요?

2021-05-31 12:13 UTC, hwookim commented on src/components/Filter.jsx
> +  }
현재는 클릭할 때만 색이 변하는데,
색이 계속 변해있길 바라신다면 클릭 이벤트 발생 시 해당 style을 변경하시면 됩니다.

참고로 사용하셨던 hide()와 show()는 style 중 display를 변경한 예입니다.

2021-05-31 12:13 UTC, hwookim commented on src/components/Filter.jsx
> +      </FilterItems>
이런 코드의 중복은 어떻게하면 제거할 수 있을까요?
이 상태라면 필터 기능 적용할 때 하나하나 다 넣어줘야겠네요.😅

2021-05-31 12:13 UTC, hwookim commented on src/components/Filter.jsx
> +  justify-content: space-between;
space-between을 할거라면 세 필터 버튼의 크기가 동일한 것이 낫지 않을까요?
지금은 뭔가 균형이 안맞아서 불편합니다..ㅎㅎ

![스크린샷 2021-05-31 오후 8 06 44](https://user-images.githubusercontent.com/45786387/120184268-bb8f5280-c24b-11eb-8ebe-cb64a9e99b69.png)

2021-05-31 12:16 UTC, GyeongyeonAn commented on src/components/Filter.jsx
> +    }
그걸 시도해보려다가 실패했긴 했습니다. 음.. 좀더 고민해볼게요

2021-05-31 12:25 UTC, GyeongyeonAn commented on src/components/Filter.jsx
> +      </FilterItems>
필터에 관한 데이터 셋(locations, prices, categories)을 각각 만들어서, map으로 하나씩 호출하는 방법이 생각이 나요. 좋은 방법이라고 생각하시나요?

2021-05-31 12:34 UTC, GyeongyeonAn commented on src/components/Filter.jsx
> +  justify-content: space-between;
padding과 폰트 크기로 버튼 크기를 조정했었는데, 지금 올려주신 방법은 padding을 지우고 width와 height를 변경하신건가요?

2021-05-31 13:37 UTC, win9612 commented
카테고리에는 양식을 빼고 일식을 넣는것보다
밑에 항목 더 추가해서 "일식", "기타" 추가해서 총 6개로 하면 좋을듯??

2021-06-03 09:17 UTC, hwookim approved these changes
#29 에서 일부 수정하도록 하겠습니다.

2021-06-03 09:25 UTC, merged